# Copyright 2022 Undistro Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -- String to partially override fullname template with a string (will prepend the release name)
nameOverride: ""
# -- String to fully override fullname template with a string
fullnameOverride: ""

# Credentials for private registries.
imageCredentials:
  # -- Specifies whether the secret should be created by providing credentials
  create: false
  # -- Docker registry host
  registry: ghcr.io
  # -- Docker registry username
  username: ""
  # -- Docker registry password
  password: ""

# -- Specify docker-registry secret names as an array to be used when `imageCredentials.create` is false
imagePullSecrets: []

ingress:
  # -- Specifies whether the ingress should be created
  enabled: false
  # -- Ingress class name
  className: ""
  # -- Annotations to be added to ingress
  annotations: {}
  # kubernetes.io/tls-acme: "true"
  # -- The host of Zora in ingress rule
  host: zora.domain
  # -- `path` and `pathType` of API in ingress rule. `path` pattern may vary according ingress controller (`/api/*` for GCE, `/api/.*` for NCP)
  server:
    path: /api
    pathType: ImplementationSpecific
  # -- `path` and `pathType` of UI in ingress rule. `path` pattern may vary according ingress controller (`/*` for GCE, `/.*` for NCP)
  ui:
    path: /
    pathType: ImplementationSpecific
  # -- The name of secret which contains keys named: `tls.crt` - the certificate; `tls.key` - the private key
  tlsSecretName: ""

operator:
  # -- Number of replicas desired of Zora operator
  replicaCount: 1
  image:
    # -- Zora operator image repository
    repository: ghcr.io/undistro/zora/operator
    # -- Overrides the image tag whose default is the chart appVersion
    tag: ""
    # -- Image pull policy
    pullPolicy: IfNotPresent
  rbac:
    # -- Specifies whether ClusterRoles and ClusterRoleBindings should be created
    create: true
    serviceAccount:
      # -- Specifies whether a service account should be created
      create: true
      # -- Annotations to be added to service account
      annotations: {}
      # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
      name: ""
  # -- Annotations to be added to pods
  podAnnotations:
    kubectl.kubernetes.io/default-container: manager
  # -- [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context) to add to the pod
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
  # -- [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context) to add to `manager` container
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
  metricsService:
    # -- Type of metrics service
    type: ClusterIP
    # -- Port of metrics service
    port: 8443
  serviceMonitor:
    # -- Specifies whether a Prometheus `ServiceMonitor` should be enabled
    enabled: false
  # -- [Resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers) to add to `manager` container
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  rbacProxy:
    image:
      # -- `kube-rbac-proxy` image repository
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      # -- `kube-rbac-proxy` image tag
      tag: v0.8.0
      # -- Image pull policy
      pullPolicy: IfNotPresent
    # -- [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context) to add to `kube-rbac-proxy` container
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    # -- [Resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers) to add to `kube-rbac-proxy` container
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
  # -- [Node selection](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node) to constrain a Pod to only be able to run on particular Node(s)
  nodeSelector: {}
  # -- [Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration) for pod assignment
  tolerations: []
  # -- Map of node/pod [affinities](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration)
  affinity: {}
  log:
    # -- Log encoding (one of 'json' or 'console')
    encoding: json
    # -- Log level to configure the verbosity of logging. Can be one of 'debug', 'info', 'error',
    # or any integer value > 0 which corresponds to custom debug levels of increasing verbosity
    level: info
    # -- Log level at and above which stacktraces are captured (one of 'info', 'error' or 'panic')
    stacktraceLevel: error
    # -- Log time encoding (one of 'epoch', 'millis', 'nano', 'iso8601', 'rfc3339' or 'rfc3339nano')
    timeEncoding: rfc3339

server:
  # -- Toggles server deployment
  enabled: true
  # -- Number of replicas desired of Zora server
  replicaCount: 1
  image:
    # -- Zora server image repository
    repository: ghcr.io/undistro/zora/server
    # -- Overrides the image tag whose default is the chart appVersion
    tag: ""
    # -- Image pull policy
    pullPolicy: IfNotPresent
  rbac:
    # -- Specifies whether ClusterRole and ClusterRoleBinding should be created
    create: true
    serviceAccount:
      # -- Specifies whether a service account should be created
      create: true
      # -- Annotations to be added to service account
      annotations: {}
      # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
      name: ""
  # -- Annotations to be added to pods
  podAnnotations: {}
  # -- [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context) to add to the pod
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65533
    runAsGroup: 65533
  # -- [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context) to add to the container
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem : true
  service:
    # -- Service type
    type: ClusterIP
    # -- Service port
    port: 8080
  # -- [Resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers) to add to the container
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  autoscaling:
    # -- Enable replica autoscaling settings
    enabled: false
    # -- Minimum replicas for the pod autoscaling
    minReplicas: 1
    # -- Maximum replicas for the pod autoscaling
    maxReplicas: 100
    # -- Percentage of CPU to consider when autoscaling
    targetCPUUtilizationPercentage: 80
    # -- Percentage of Memory to consider when autoscaling
    targetMemoryUtilizationPercentage: ""
  # -- [Node selection](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node) to constrain a Pod to only be able to run on particular Node(s)
  nodeSelector: {}
  # -- [Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration) for pod assignment
  tolerations: []
  # -- Map of node/pod [affinities](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration)
  affinity: {}
  log:
    # -- Log encoding (one of 'json' or 'console')
    encoding: json
    # -- Log level to configure the verbosity of logging. Can be one of 'debug', 'info', 'error',
    # or any integer value > 0 which corresponds to custom debug levels of increasing verbosity
    level: info
    # -- Log level at and above which stacktraces are captured (one of 'info', 'error' or 'panic')
    stacktraceLevel: error
    # -- Log time encoding (one of 'epoch', 'millis', 'nano', 'iso8601', 'rfc3339' or 'rfc3339nano')
    timeEncoding: rfc3339

ui:
  # -- Toggles UI deployment
  enabled: true
  # -- Number of replicas desired of Zora UI
  replicaCount: 1
  image:
    # -- Zora UI image repository
    repository: ghcr.io/undistro/zora/ui
    # -- Overrides the image tag whose default is the chart appVersion
    tag: ""
    # -- Image pull policy
    pullPolicy: IfNotPresent
  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Annotations to be added to service account
    annotations: {}
    # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
    name: ""
  # -- Annotations to be added to pods
  podAnnotations: {}
  # -- [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context) to add to the pod
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
  # -- [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context) to add to the container
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
  service:
    # -- Service type
    type: ClusterIP
    # -- Service port
    port: 8080
  # -- [Resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers) to add to the container
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  autoscaling:
    # -- Enable replica autoscaling settings
    enabled: false
    # -- Minimum replicas for the pod autoscaling
    minReplicas: 1
    # -- Maximum replicas for the pod autoscaling
    maxReplicas: 100
    # -- Percentage of CPU to consider when autoscaling
    targetCPUUtilizationPercentage: 80
    # -- Percentage of Memory to consider when autoscaling
    targetMemoryUtilizationPercentage: ""
  # -- [Node selection](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node) to constrain a Pod to only be able to run on particular Node(s)
  nodeSelector: {}
  # -- [Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration) for pod assignment
  tolerations: []
  # -- Map of node/pod [affinities](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration)
  affinity: {}

nginx:
  # -- Number of replicas desired of nginx
  replicaCount: 1
  image:
    # -- NGINX image repository
    repository: nginx
    # -- NGINX image tag
    tag: 1.20.2-alpine
    # -- Image pull policy
    pullPolicy: IfNotPresent
  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Annotations to be added to service account
    annotations: {}
    # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
    name: ""
  # -- Annotations to be added to pods
  podAnnotations: {}
  # -- [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context) to add to the pod
  podSecurityContext:
    runAsNonRoot: true
    runAsGroup: 10000
    runAsUser: 10000
    fsGroup: 10000
  # -- [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context) to add to the container
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem : false
  service:
    # -- Service type
    type: ClusterIP
    # -- Service port
    port: 80
  # -- [Resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers) to add to the container
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  autoscaling:
    # -- Enable replica autoscaling settings
    enabled: false
    # -- Minimum replicas for the pod autoscaling
    minReplicas: 1
    # -- Maximum replicas for the pod autoscaling
    maxReplicas: 100
    # -- Percentage of CPU to consider when autoscaling
    targetCPUUtilizationPercentage: 80
    # -- Percentage of Memory to consider when autoscaling
    targetMemoryUtilizationPercentage: ""
  # -- [Node selection](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node) to constrain a Pod to only be able to run on particular Node(s)
  nodeSelector: {}
  # -- [Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration) for pod assignment
  tolerations: []
  # -- Map of node/pod [affinities](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration)
  affinity: {}

scan:
  worker:
    image:
      # -- worker image repository
      repository: ghcr.io/undistro/zora/worker
      # -- Overrides the image tag whose default is the chart appVersion
      tag: ""
  # -- Names of the default plugins
  defaultPlugins:
    - popeye
  plugins:
    popeye:
      image:
        # -- popeye plugin image repository
        repository: derailed/popeye
        # -- popeye plugin image tag
        tag: v0.10.0
    kubescape:
      image:
        # -- kubescape plugin image repository
        repository: quay.io/armosec/kubescape
        # -- kubescape plugin image tag
        tag: v2.0.163
