{{- if not .Values.ingress.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zora.fullname" . }}-nginx
  labels:
    {{- include "zora.nginxLabels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zora.nginxSelectorLabels" . | nindent 4 }}
{{- end }}
