ui:
  image:
    tag: saas-0.1.1
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production-http01
  enabled: true
  className: nginx
  host: zora-dashboard.undistro.io
  tlsSecretName: zora-saas-cert
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 4m
    memory: 30Mi
imagePullSecrets:
  - name: zora-saas-registry-cred
storage: "mongo"
mongo:
  database: "zora-saas-prod"
log:
  level: info
proxy:
  enabled: false
monitor:
  enabled: true
