# Copyright 2022 Undistro Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{ if and .Values.server.enabled .Values.server.rbac.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zora.serverServiceAccountName" . }}
  labels:
    {{- include "zora.serverLabels" . | nindent 4 }}
  {{- with .Values.server.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}
{{- if .Values.server.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "zora.serverServiceAccountName" . }}
rules:
  - apiGroups:
      - zora.undistro.io
    resources:
      - clusters
      - clusterissues
      - clusterscans
      - plugins
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - zora.undistro.io
    resources:
      - clusters/status
      - clusterscans/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "zora.serverServiceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "zora.serverServiceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "zora.serverServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
