apiVersion: v1
kind: Service
metadata:
  name: {{ include "zora.fullname" . }}-server
  labels:
    {{- include "zora.serverLabels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zora.serverSelectorLabels" . | nindent 4 }}
