{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zora-saas.serviceAccountName" . }}
  labels:
    {{- include "zora-saas.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: saas-proxy-client
  labels:
    {{- include "zora-saas.labels" . | nindent 4 }}
{{- end }}
